clc
close all
scrsz = get(0,'ScreenSize');
figure( 'WindowStyle', 'normal', ...  %%%'normal'
                  'Visible'     ,'on', ...
                  'NumberTitle' ,'off', ...
                  'Name'        ,'Wrong format', ...
                  'Resize'      ,'on', ...
                  'Colormap'    ,[], ...
                  'MenuBar'     ,'none',...
                  'ToolBar' 	,'none', ...
                 'OuterPosition',[scrsz(4)/2 scrsz(4)/5 scrsz(3)/1.9 scrsz(4)/1.61]);
plot(2000,800,'.w')
hold on
plot(1,1,'.w')
text(10,400,['\fontsize{12} Data set must be of type {\bf structure array} named "par" ',...
 '\newline The structure must contain the fields:',...
 '\newline par.pkmatrix – array of numerical data with row-measurements \newline and columns- data coordinates.',...
 '\newline par.pkdesc - contains two cells par.pkdesc.desc, and par.pkdesc.units',...
 '\newline par.pkdesc.desc - gives a description of the pkmatrix-columns \newline with at least the following string variables:',...
 '\newline "frame"; "x"; "y"; "z"; "pa";  paz"; "intensity"',... 
 '\newline where pa is position accuracy of xy localization and \newline paz is position accuracy on z-axis  localization, frame is frame number.',...
 '\newline\newline par.pkdesc.units contains a description  of the units of measure \newline for each column in string format.',...
'\newline \newline If you do not have data with this structure then use \newline IMPORT DATA FROM EXCEL  from menu.'...
])



title ('\fontsize{16} Wrong Data-Format')
whitebg('w')
axis off
btn = uicontrol('Style', 'pushbutton', 'String', 'CLOSE',...
        'Position', [20 20 150 40],...
        'Callback','a_close_info');
clear('ax','btn','scrsz','options')

clc

