
clc
close all
scrsz = get(0,'ScreenSize');

figure( 'WindowStyle', 'normal', ...  %%%'normal'
                  'Visible'     ,'on', ...
                  'NumberTitle' ,'off', ...
                  'Name'        ,'Ripley', ...
                  'Resize'      ,'on', ...
                  'Colormap'    ,[], ...
                  'MenuBar'     ,'none',...
                  'ToolBar' 	,'none', ...
                 'OuterPosition',[scrsz(3)/5 scrsz(4)/4 scrsz(3)/1.9 scrsz(4)/2.61]);
plot(2000,60,'.w')
hold on
plot(1,1,'.w')
text(10,30,['\fontsize{12}The result for only one pair of samples:',...
'\newline p value of KS test for Ripley K-function distribution = ',num2str(p_val_K_singel),...
'\newline p value of WX test for Ripley K-function distribution = ',num2str(p_val_W_singel)]);

title ('\fontsize{16} The Ripley K-functions comparison for only one pair of samples')
whitebg('w')
axis off
btn = uicontrol('Style', 'pushbutton', 'String', 'CLOSE',...
        'Position', [20 20 150 40],...
        'Callback','close');
clear('ax','btn','scrsz')

clc

