
clear('c','i','in','INN','k','L','M','missc','n','net',...
'NeuronNumber','no_pair','options','ou','out','OUU','para_nr',...
'prob','prob2','scr','scrsz',...   
'test_nr','testname','texnam','u','ww');
 close;