
scrsz = get(0,'ScreenSize');
figure('WindowStyle', 'normal', ...  %%%'normal'
                  'Visible'     ,'on', ...
                  'NumberTitle' ,'off', ...
                  'Name'        ,'MLP', ...
                  'Resize'      ,'on', ...
                  'Colormap'    ,[], ...
                  'MenuBar'     ,'none',...
                  'ToolBar' 	,'none', ...
                 'OuterPosition',[scrsz(3)/4 scrsz(4)/3 scrsz(3)/1.9 scrsz(4)/1.6]);
                 
whitebg('w')                 


text(0.05,0.5,['\fontsize{12} This test cannot be used to extend a MLP neural network training data',...
  '\newline because the expected (target) similarity classification is not given.',...
 '\newline \newline You can verify this test-data using the current network MLP',...
 '\newline and if you are sure that the suggested classification is correct '...
 '\newline you can use the network output as the expected (target) similarity classification.',...
 '\newline \newline',...
 '\newline In order to do this, you have to \newline - test the data on the current MLP network ( button NEW TEST DATA)'...                                  
'\newline - repeat the update for the test data and enter the MLP result as \newline   the expected similarity classification. (SIMILAR or DISSIMILAR button).'
])

title ('\fontsize{16} No target similarity classification')
whitebg('w')
axis off
btn = uicontrol('Style', 'pushbutton', 'String', 'CLOSE',...
        'Position', [20 20 150 40],...
        'Callback', 'mlp_close_info_update');
clear('ax','btn')

clc

