 
 
clear('av_tot','avg_pm', 'avg_pmc','CI','CIMR', 'CIMRc', 'CIripK' ,'crm', 'dis', 'lm1', 'lm2', 'Nmin',...
'options', 'PP', 'PVMR' ,'PVMRc', 'PVR', 'PVRc',...
'siml_r', 'simlc_r', 'simm_r', 'simmc_r' ,'zero','tpw','mpv')

 clear('ff','xf','K1','K2','L11','L12','box_ripl1','box_ripl2',...
'dato1','dato2','h','i','Nm1','p','pos1','pos2','rmin1','rmin2','s',...
'scrsz','wait_h','c0','cr','d1','d2','E','km1','km2','rmax')

clear('av_tot','avg_pm', 'avg_pmc','CI','CIMR', 'CIMRc', 'CIripK' ,'crm', 'dis', 'lm1', 'lm2', 'Nmin',...
'options', 'PP', 'PVMR' ,'PVMRc', 'PVR', 'PVRc',...
'siml_r', 'simlc_r', 'simm_r', 'simmc_r' ,'zero')
