save('all_compar.mat','all_ks_dens','all_wilcox_dens','all_ave_dens1',...
'all_ave_dens2','all_ave_dens_ks','all_ks_curv',...
'all_wilcox_curv','all_ave_curv1','all_ave_curv2',...
'all_ave_curv_ks','all_ks_ripl','dist','all_ks_conc')